# bot.py
# Main Discord bot for "Nhanh Như Chớp"
# Requirements:
# - discord.py (v2.x) with message_content intent enabled
# - asyncio for non-blocking sleeps
# - questions.json (generated by generate_questions.py)
# - data.json to persist scores
# - keep_alive.py runs separately if desired

import discord
from discord.ext import commands, tasks
import asyncio
import json
import random
import os
import unicodedata
import re

# ---------- Configuration ----------
COMMAND_PREFIX = "!"
QUESTIONS_FILE = "import_questions.py"
DATA_FILE = "data.json"
TOP_ROLES = [("VIP", 1), ("PRO", 2), ("NOOB", 3)]  # role name and rank position
ROUND_QUESTIONS = 5
QUESTION_TIMEOUT = 30  # seconds to answer each question
AFTER_ANSWER_DELAY = 5  # seconds after correct/timeout before next question

# Load token from environment variable. Set DISCORD_BOT_TOKEN before running.
TOKEN = os.environ.get("DISCORD_BOT_TOKEN") or "YOUR_BOT_TOKEN_HERE"

intents = discord.Intents.all()  # message_content must be True here
bot = commands.Bot(command_prefix=COMMAND_PREFIX, intents=intents, help_command=None)

# In-memory structures
questions = []
scores = {}  # user_id (str) -> int
game_states = {}  # guild_id -> state dict

# Utilities
def load_questions():
    global questions
    if not os.path.exists(QUESTIONS_FILE):
        raise FileNotFoundError(f"{QUESTIONS_FILE} not found. Run generate_questions.py first.")
    with open(QUESTIONS_FILE, "r", encoding="utf-8") as f:
        questions = json.load(f)
    if not isinstance(questions, list) or len(questions) < 5:
        raise ValueError("questions.json must be a list with at least 5 items.")
    # ensure format
    for item in questions:
        if "q" not in item or "a" not in item:
            raise ValueError("Each question must have 'q' and 'a' fields.")

def load_scores():
    global scores
    if os.path.exists(DATA_FILE):
        with open(DATA_FILE, "r", encoding="utf-8") as f:
            try:
                scores = json.load(f)
            except json.JSONDecodeError:
                scores = {}
    else:
        scores = {}

def save_scores():
    with open(DATA_FILE, "w", encoding="utf-8") as f:
        json.dump(scores, f, ensure_ascii=False, indent=2)

def normalize_text(s: str) -> str:
    # Lowercase, remove diacritics, non-alphanumeric characters, and spaces
    s = s.strip().lower()
    s = unicodedata.normalize('NFD', s)
    s = ''.join(ch for ch in s if not unicodedata.category(ch).startswith('M'))  # remove diacritics
    s = re.sub(r'[^0-9a-zA-Z\u00C0-\u024F]+', '', s)  # remove non word characters
    return s

def word_count(answer: str) -> int:
    # Count words by splitting on whitespace
    return max(1, len([w for w in answer.strip().split() if w]))

# Game state helpers
def init_state(guild_id):
    state = {
        "active": False,
        "task": None,
        "channel_id": None,
        "questions": [],
        "current_index": 0,
        "stop_flag": False,
        "skip_flag": False,
    }
    game_states[guild_id] = state
    return state

def get_state(guild_id):
    return game_states.get(guild_id) or init_state(guild_id)

# Role management functions
async def ensure_roles(guild: discord.Guild):
    created = []
    for role_name, _ in TOP_ROLES:
        role = discord.utils.get(guild.roles, name=role_name)
        if role is None:
            try:
                role = await guild.create_role(name=role_name)
                created.append(role_name)
            except discord.Forbidden:
                # cannot create role
                pass
    return created

async def sync_roles_for_guild(guild: discord.Guild):
    # Ensure the roles exist
    await ensure_roles(guild)
    # Load leaderboard
    leaderboard = sorted(scores.items(), key=lambda kv: kv[1], reverse=True)
    top3 = [int(uid) for uid, _ in leaderboard[:3]]
    # Map ranks to role names
    rank_role = {1: "VIP", 2: "PRO", 3: "NOOB"}
    # Iterate members who currently have any of the managed roles and remove them if needed
    for member in guild.members:
        # skip bots
        if member.bot:
            continue
        to_add = []
        to_remove = []
        # determine desired role for this member
        desired_role = None
        try:
            idx = top3.index(member.id)
            desired_role = rank_role[idx + 1]
        except ValueError:
            desired_role = None
        # check current roles
        for role_name, _ in TOP_ROLES:
            role = discord.utils.get(guild.roles, name=role_name)
            if role is None:
                continue
            if desired_role == role_name:
                if role not in member.roles:
                    to_add.append(role)
            else:
                if role in member.roles:
                    to_remove.append(role)
        # Apply changes
        if to_add:
            try:
                await member.add_roles(*to_add, reason="Leaderboard role assignment")
            except discord.Forbidden:
                pass
        if to_remove:
            try:
                await member.remove_roles(*to_remove, reason="Leaderboard role update")
            except discord.Forbidden:
                pass

async def update_roles_all_guilds():
    for guild in bot.guilds:
        await sync_roles_for_guild(guild)

# Bot events and commands
@bot.event
async def on_ready():
    load_questions()
    load_scores()
    print(f"Bot logged in as {bot.user} (id: {bot.user.id})")
    print("Loaded questions:", len(questions))
    print("Loaded scores entries:", len(scores))
    # Optionally sync roles once on startup
    await update_roles_all_guilds()

@bot.event
async def on_guild_join(guild):
    # initialize state for new guild
    init_state(guild.id)
    await ensure_roles(guild)

# Custom help embed
@bot.command(name="help")
async def help_command(ctx):
    embed = discord.Embed(title="Nhanh Như Chớp — Hướng dẫn & Lệnh", color=0x3498db)
    embed.add_field(name="Mục tiêu", value="Trả lời nhanh 5 câu đố. Mỗi câu đúng +3 điểm, sai -1 điểm.", inline=False)
    embed.add_field(name="Lưu ý trả lời", value="Bot lắng nghe tin nhắn trong kênh nơi dùng lệnh !start. Không cần DM bot.", inline=False)
    embed.add_field(name="Lệnh", value=(
        "`!start` — Bắt đầu vòng 5 câu.\n"
        "`!stop` — Hủy vòng hiện tại ngay lập tức.\n"
        "`!next` — Bỏ qua câu hiện tại, chuyển sang câu tiếp theo.\n"
        "`!score` — Xem Top 10 bảng xếp hạng.\n"
        "`!help` — Hiện trang hướng dẫn này."
    ), inline=False)
    embed.set_footer(text="Gợi ý hiển thị số từ của đáp án cho mỗi câu.")
    await ctx.send(embed=embed)

@bot.command(name="score")
async def score_command(ctx):
    # Top 10 leaderboard
    load_scores()
    leaderboard = sorted(scores.items(), key=lambda kv: kv[1], reverse=True)[:10]
    if not leaderboard:
        embed = discord.Embed(title="Top 10 — Bảng xếp hạng", description="Chưa có điểm nào.", color=0x2ecc71)
        await ctx.send(embed=embed)
        return
    desc = ""
    pos = 1
    for uid, pts in leaderboard:
        member = ctx.guild.get_member(int(uid))
        name = member.display_name if member else f"<user id {uid}>"
        desc += f"{pos}. {name} — {pts} điểm\n"
        pos += 1
    embed = discord.Embed(title="Top 10 — Bảng xếp hạng", description=desc, color=0x2ecc71)
    await ctx.send(embed=embed)

@bot.command(name="start")
async def start_command(ctx):
    guild_id = ctx.guild.id
    state = get_state(guild_id)
    if state["active"]:
        await ctx.send("Một vòng đang diễn ra. Vui lòng đợi hoặc dùng `!stop` để hủy.")
        return
    # select RANDOM 5 questions for this round
    selected = random.sample(questions, k=ROUND_QUESTIONS)
    state["active"] = True
    state["questions"] = selected
    state["current_index"] = 0
    state["channel_id"] = ctx.channel.id
    state["stop_flag"] = False
    state["skip_flag"] = False

    # start the round without blocking
    state["task"] = asyncio.create_task(run_round(ctx.guild, ctx.channel))
    await ctx.send(f"Vòng mới bắt đầu — 5 câu! Chơi ngay ở kênh này. Bot sẽ lắng nghe câu trả lời trong kênh.")

@bot.command(name="stop")
async def stop_command(ctx):
    guild_id = ctx.guild.id
    state = get_state(guild_id)
    if not state["active"]:
        await ctx.send("Không có vòng chơi nào đang chạy.")
        return
    state["stop_flag"] = True
    # cancel the task if exists
    if state["task"]:
        try:
            state["task"].cancel()
        except:
            pass
    state["active"] = False
    await ctx.send("Vòng chơi đã bị hủy bởi quản trị viên/người chơi.")

@bot.command(name="next")
async def next_command(ctx):
    guild_id = ctx.guild.id
    state = get_state(guild_id)
    if not state["active"]:
        await ctx.send("Không có vòng chơi nào đang chạy.")
        return
    state["skip_flag"] = True
    await ctx.send("Bỏ qua câu hiện tại, chuyển sang câu tiếp theo...")

# Core round coroutine
async def run_round(guild: discord.Guild, channel: discord.TextChannel):
    guild_id = guild.id
    state = get_state(guild_id)
    try:
        for idx in range(ROUND_QUESTIONS):
            if state["stop_flag"]:
                break
            state["current_index"] = idx
            qitem = state["questions"][idx]
            q_text = qitem["q"]
            answer = qitem["a"]
            hint_words = word_count(answer)
            await channel.send(f"Câu hỏi {idx+1}/{ROUND_QUESTIONS}: {q_text} | 💡 Gợi ý: {hint_words} từ")
            start_time = asyncio.get_event_loop().time()
            answered = False
            # Loop receiving messages until correct or timeout or stopped or skipped
            while True:
                if state["stop_flag"]:
                    break
                if state["skip_flag"]:
                    state["skip_flag"] = False
                    await channel.send(f"Đã bỏ qua. Đáp án: **{answer}**")
                    await asyncio.sleep(AFTER_ANSWER_DELAY)
                    break
                elapsed = asyncio.get_event_loop().time() - start_time
                remaining = QUESTION_TIMEOUT - elapsed
                if remaining <= 0:
                    await channel.send(f"⏰ Hết thời gian! Đáp án: **{answer}**")
                    await asyncio.sleep(AFTER_ANSWER_DELAY)
                    break
                try:
                    def check(m: discord.Message):
                        # Only consider messages in the same channel, not from bots
                        return (
                            m.channel.id == channel.id
                            and not m.author.bot
                        )
                    msg = await bot.wait_for("message", timeout=remaining, check=check)
                except asyncio.TimeoutError:
                    # handled by next loop iteration where remaining <=0
                    continue
                # Process the message
                # Normalize and compare
                guess_norm = normalize_text(msg.content)
                ans_norm = normalize_text(answer)
                if guess_norm == ans_norm:
                    # Correct answer
                    uid_str = str(msg.author.id)
                    scores[uid_str] = int(scores.get(uid_str, 0)) + 3
                    save_scores()
                    await channel.send(f"🎉 Đúng rồi — {msg.author.mention} nhận +3 điểm! Đáp án: **{answer}**")
                    # update roles now that scores changed
                    await sync_roles_for_guild(guild)
                    await asyncio.sleep(AFTER_ANSWER_DELAY)
                    answered = True
                    break
                else:
                    # Wrong answer
                    uid_str = str(msg.author.id)
                    scores[uid_str] = int(scores.get(uid_str, 0)) - 1
                    save_scores()
                    await channel.send(f"❌ Sai rồi — {msg.author.mention} bị -1 điểm.")
                    # continue waiting until timeout or correct
                    # roles updated in case scores changed players
                    await sync_roles_for_guild(guild)
                    continue
            # proceed to next question
            continue
    except asyncio.CancelledError:
        # Round canceled externally
        pass
    finally:
        # Round ended: reset state
        state["active"] = False
        state["task"] = None
        state["questions"] = []
        state["current_index"] = 0
        state["channel_id"] = None
        state["stop_flag"] = False
        state["skip_flag"] = False
        await channel.send("Vòng chơi kết thúc.")
        # Final role sync at end
        await sync_roles_for_guild(guild)

# Keep persistence autosave task if desired (not essential but safe)
@tasks.loop(minutes=1)
async def autosave_scores():
    save_scores()

@bot.event
async def on_message(message):
    # allow commands to be processed
    await bot.process_commands(message)

# Start tasks on startup
@bot.event
async def on_connect():
    if not autosave_scores.is_running():
        autosave_scores.start()

if __name__ == "__main__":
    # Ensure data files exist
    if not os.path.exists(QUESTIONS_FILE):
        print(f"Error: {QUESTIONS_FILE} not found. Run generate_questions.py to create it.")
    load_questions()
    load_scores()
    bot.run()
